namespace Recruitly.Common.Mediator;

/// <summary>
/// Defines a handler interface for processing commands that result in an operation outcome,
/// encapsulated within a <see cref="Result"/> or <see cref="Result{TResponse}"/>.
/// </summary>
/// <typeparam name="TCommand">The type of the command to be handled.</typeparam>
public interface ICommandHandler<in TCommand> : IRequestHandler<TCommand, Result>
    where TCommand : ICommand;

/// <summary>
/// Defines a handler interface for processing commands that result in an operation outcome,
/// encapsulated within a <see cref="Result"/>.
/// </summary>
/// <typeparam name="TCommand">The type of the command to be handled.</typeparam>
/// <typeparam name="TResponse">
/// The type of the response generated by the command handler.
/// </typeparam>
public interface ICommandHandler<in TCommand, TResponse> : IRequestHandler<TCommand, Result<TResponse>>
    where TCommand : ICommand<TResponse>;
