namespace Recruitly.Common.Mediator;

/// <summary>
/// Represents a handler for processing queries within a mediator pattern.
/// </summary>
/// <typeparam name="TQuery">
/// The type of the query to be handled. Must implement <see cref="IQuery{TResponse}"/>.
/// </typeparam>
/// <typeparam name="TResponse">The type of the response generated by the query handler.</typeparam>
public interface IQueryHandler<in TQuery, TResponse> : IRequestHandler<TQuery, Result<TResponse>>
    where TQuery : IQuery<TResponse>;
